sudo: true
language: node_js
node_js:
  - '6'
cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache
before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
install: yarn
script: yarn test
after_success:
  - npm run coverage
  - npm run semantic-release
  - npm run reparo
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
